using CmdAi.Core.Interfaces;
using CmdAi.Core.Models;

namespace CmdAi.Core.Services;

public class AICommandResolver : ICommandResolver
{
    private readonly IAIProvider _aiProvider;
    private readonly ICommandValidator _validator;
    private readonly ILearningService _learningService;
    private readonly PatternCommandResolver _fallbackResolver;
    private readonly AIConfiguration _config;

    public AICommandResolver(
        IAIProvider aiProvider,
        ICommandValidator validator,
        ILearningService learningService,
        PatternCommandResolver fallbackResolver,
        AIConfiguration config)
    {
        _aiProvider = aiProvider;
        _validator = validator;
        _learningService = learningService;
        _fallbackResolver = fallbackResolver;
        _config = config;
    }

    public bool CanResolve(string tool)
    {
        // AI resolver can attempt any tool
        return true;
    }

    public async Task<CommandResult?> ResolveCommandAsync(CommandRequest request, CommandContext context)
    {
        CommandResult? result = null;

        // Try AI resolution first if enabled and available
        if (_config.EnableAI)
        {
            result = await TryAIResolutionAsync(request, context);
        }

        // Fall back to pattern matching if AI fails or is disabled
        if (result == null && _config.FallbackToPatterns && _fallbackResolver.CanResolve(request.Tool))
        {
            result = await _fallbackResolver.ResolveCommandAsync(request, context);
            if (result != null)
            {
                result = result with { Context = $"{result.Context} (AI unavailable, using patterns)" };
            }
        }

        return result;
    }

    private async Task<CommandResult?> TryAIResolutionAsync(CommandRequest request, CommandContext context)
    {
        try
        {
            // Check if AI provider is available
            var isAvailable = await _aiProvider.IsAvailableAsync();
            if (!isAvailable)
            {
                return null;
            }

            // Get relevant examples from learning service
            var relevantExamples = await _learningService.GetRelevantExamplesAsync(request.Tool, request.Query);
            
            // Build context for AI
            var aiContext = BuildAIContext(request, context, relevantExamples);
            
            // Generate command using AI
            var command = await _aiProvider.GenerateCommandAsync(request.Tool, request.Query, aiContext);
            
            if (string.IsNullOrWhiteSpace(command))
            {
                return null;
            }

            // Validate the generated command
            var validation = await _validator.ValidateCommandAsync(command, request.Tool);
            
            if (!validation.IsValid)
            {
                return null;
            }

            // Create result with AI-specific context
            var description = $"AI-generated {request.Tool} command";
            var resultContext = $"Generated by {_aiProvider.ModelName}";
            
            if (!validation.IsSafe)
            {
                resultContext += " ⚠️ POTENTIALLY UNSAFE";
                description += " (requires careful review)";
            }

            if (validation.Warnings?.Any() == true)
            {
                resultContext += $" | Warnings: {string.Join(", ", validation.Warnings)}";
            }

            return new CommandResult(command, description, true, resultContext);
        }
        catch (TimeoutException)
        {
            return null; // Will fall back to patterns
        }
        catch (Exception)
        {
            return null; // Will fall back to patterns
        }
    }

    private string BuildAIContext(CommandRequest request, CommandContext context, IEnumerable<LearningEntry> relevantExamples)
    {
        var contextParts = new List<string>();

        // Add working directory context
        if (!string.IsNullOrEmpty(context.WorkingDirectory))
        {
            contextParts.Add($"Working directory: {context.WorkingDirectory}");
        }

        // Add git repository context
        if (context.IsGitRepository)
        {
            contextParts.Add("In a Git repository");
        }

        // Add relevant examples from learning
        if (relevantExamples.Any())
        {
            contextParts.Add("Similar successful commands:");
            foreach (var example in relevantExamples.Take(3))
            {
                contextParts.Add($"'{example.Query}' → {example.Command}");
            }
        }

        return string.Join(". ", contextParts);
    }
}