using CmdAi.Core.Interfaces;
using CmdAi.Core.Models;

namespace CmdAi.Core.Services;

public class MultiProviderAICommandResolver : ICommandResolver, IResolutionDiagnostics
{
    private readonly IEnumerable<IAIProvider> _aiProviders;
    private readonly ICommandValidator _validator;
    private readonly ILearningService _learningService;
    private readonly PatternCommandResolver _fallbackResolver;
    private readonly AIConfiguration _config;
    private readonly object _traceLock = new();
    private List<ProviderAttemptDiagnostics> _lastTrace = [];

    public MultiProviderAICommandResolver(
        IEnumerable<IAIProvider> aiProviders,
        ICommandValidator validator,
        ILearningService learningService,
        PatternCommandResolver fallbackResolver,
        AIConfiguration config)
    {
        _aiProviders = aiProviders;
        _validator = validator;
        _learningService = learningService;
        _fallbackResolver = fallbackResolver;
        _config = config;
    }

    public bool CanResolve(string tool)
    {
        return true;
    }

    public IReadOnlyList<ProviderAttemptDiagnostics> GetLastResolutionTrace()
    {
        lock (_traceLock)
        {
            return _lastTrace.ToList();
        }
    }

    public async Task<CommandResult?> ResolveCommandAsync(CommandRequest request, CommandContext context)
    {
        var attempts = new List<ProviderAttemptDiagnostics>();
        CommandResult? result = null;

        // Try AI resolution with provider priority if enabled
        if (_config.EnableAI)
        {
            result = await TryAIResolutionWithPriorityAsync(request, context, attempts);
        }

        // Fall back to pattern matching if AI fails or is disabled
        if (result == null && _config.FallbackToPatterns && _fallbackResolver.CanResolve(request.Tool))
        {
            result = await _fallbackResolver.ResolveCommandAsync(request, context);
            if (result != null)
            {
                result = result with { Context = $"{result.Context} (AI unavailable, using patterns)" };
            }
        }

        UpdateTrace(attempts);
        return result;
    }

    private async Task<CommandResult?> TryAIResolutionWithPriorityAsync(
        CommandRequest request,
        CommandContext context,
        List<ProviderAttemptDiagnostics> attempts)
    {
        var providers = GetOrderedProviders();

        foreach (var provider in providers)
        {
            try
            {
                var result = await TryProviderAsync(provider, request, context);
                if (result != null)
                {
                    attempts.Add(new ProviderAttemptDiagnostics(provider.ProviderId, provider.ModelName, true, true));
                    return result;
                }

                attempts.Add(new ProviderAttemptDiagnostics(provider.ProviderId, provider.ModelName, true, false, ProviderFailureType.Unknown, "No command returned"));
            }
            catch (AIProviderException ex)
            {
                attempts.Add(new ProviderAttemptDiagnostics(provider.ProviderId, provider.ModelName, true, false, ex.FailureType, ex.Message));
                if (ex.IsTransient)
                {
                    continue;
                }

                // Permanent failures do not move to next provider.
                break;
            }
            catch (Exception ex)
            {
                attempts.Add(new ProviderAttemptDiagnostics(provider.ProviderId, provider.ModelName, true, false, ProviderFailureType.Unknown, ex.Message));
                continue;
            }
        }

        return null;
    }

    private async Task<CommandResult?> TryProviderAsync(IAIProvider provider, CommandRequest request, CommandContext context)
    {
        // Check if provider is available
        var isAvailable = await provider.IsAvailableAsync();
        if (!isAvailable)
        {
            throw new AIProviderException(provider.ProviderId, ProviderFailureType.Configuration, "Provider unavailable or missing configuration");
        }

        // Get relevant examples from learning service
        var relevantExamples = await _learningService.GetRelevantExamplesAsync(request.Tool, request.Query);

        // Build context for AI
        var aiContext = BuildAIContext(request, context, relevantExamples);

        // Generate command using AI
        var command = await provider.GenerateCommandAsync(request.Tool, request.Query, aiContext);

        if (string.IsNullOrWhiteSpace(command))
        {
            return null;
        }

        // Validate the generated command
        var validation = await _validator.ValidateCommandAsync(command, request.Tool);

        if (!validation.IsValid)
        {
            return null;
        }

        // Create result with AI-specific context
        var description = $"AI-generated {request.Tool} command";
        var resultContext = $"Generated by {provider.ModelName}";

        if (!validation.IsSafe)
        {
            resultContext += " ⚠️ POTENTIALLY UNSAFE";
            description += " (requires careful review)";
        }

        if (validation.Warnings?.Any() == true)
        {
            resultContext += $" | Warnings: {string.Join(", ", validation.Warnings)}";
        }

        return new CommandResult(command, description, true, resultContext);
    }

    private IEnumerable<IAIProvider> GetOrderedProviders()
    {
        var configuredProviders = _config.GetProviders();
        var orderedProviders = new List<IAIProvider>();

        // Order providers based on configuration priority
        foreach (var providerName in configuredProviders)
        {
            var provider = _aiProviders.FirstOrDefault(p =>
                p.ProviderId.Equals(providerName, StringComparison.OrdinalIgnoreCase));
            var providerConfig = _config.GetProviderConfiguration(providerName);
            if (provider != null && providerConfig?.Enabled == true)
            {
                orderedProviders.Add(provider);
            }
        }

        // Add any remaining enabled providers not explicitly configured.
        var remainingProviders = _aiProviders.Where(p =>
            !orderedProviders.Contains(p) &&
            _config.GetProviderConfiguration(p.ProviderId)?.Enabled == true);
        orderedProviders.AddRange(remainingProviders);

        return orderedProviders;
    }

    private string BuildAIContext(CommandRequest request, CommandContext context, IEnumerable<LearningEntry> relevantExamples)
    {
        var contextParts = new List<string>();

        // Add working directory context
        if (!string.IsNullOrEmpty(context.WorkingDirectory))
        {
            contextParts.Add($"Working directory: {context.WorkingDirectory}");
        }

        // Add git repository context
        if (context.IsGitRepository)
        {
            contextParts.Add("In a Git repository");
        }

        // Add relevant examples from learning
        if (relevantExamples.Any())
        {
            contextParts.Add("Similar successful commands:");
            foreach (var example in relevantExamples.Take(3))
            {
                contextParts.Add($"'{example.Query}' → {example.Command}");
            }
        }

        return string.Join(". ", contextParts);
    }

    private void UpdateTrace(List<ProviderAttemptDiagnostics> attempts)
    {
        lock (_traceLock)
        {
            _lastTrace = attempts;
        }
    }
}
